grafana:
  enabled: false   # still deploying Grafana separately

alertmanager:
  service:
    type: NodePort
    nodePort: 30903   # optional fixed port

prometheus:
  service:
    type: NodePort
    nodePort: 30900   # optional fixed port
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
