apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: https://github.com/ka1ox/my-k8s-apps.git
    targetRevision: main
    path: apps/myapps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
