apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.3.0
    helm:
      values: |
          crds:
            enabled: false   # 🚀 skip installing CRDs here
        admissionWebhooks:
          patch:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: true
        grafana:
          service:
            type: NodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
