apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/ka1ox/my-k8s-apps.git
    targetRevision: main
    path: crds
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
