apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.5.3
    helm:
      releaseName: test-nginx
      values: |
        service:
          type: NodePort
          nodePorts:
            http: 30081
        replicaCount: 1

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring      # install ServiceMonitor in monitoring ns
            interval: 30s
            scrapeTimeout: 10s
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
