apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx
    path: deploy/static/provider/cloud
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
