apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.5.3
    helm:
      releaseName: test-nginx
      values: |
        service:
          type: NodePort
          nodePorts:
            http: 30081
        replicaCount: 1

        # Add Prometheus exporter sidecar
        metrics:
          enabled: true
          service:
            type: ClusterIP
            port: 9113
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# ServiceMonitor to scrape metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-nginx
  namespaceSelector:
    matchNames:
      - test
  endpoints:
    - port: metrics
      interval: 30s
