apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: test-nginx
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
