apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/ka1ox/my-k8s-apps.git
    path: apps/test-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
