apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd   # ArgoCD always lives in argocd namespace
spec:
  project: monitoring # or "default" if your AppProject doesn't allow "test" namespace yet
  source:
    repoURL: https://charts.bitnami.com/bitnami   # example public Helm repo
    chart: nginx
    targetRevision: 15.5.3                        # pick a stable version
    helm:
      releaseName: test-nginx
      values: |
        service:
          type: NodePort
          nodePorts:
            http: 30080
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
