apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: https://github.com/ka1ox/my-k8s-apps.git
    targetRevision: main
    path: apps/argocd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:               # ✅ must be inside syncPolicy
      - CreateNamespace=true
